
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allocationdb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none #none
    show-sql: true
    properties:
       hibernate:
         jdbc:
           time_zone: UTC
         show_sql: true
         format_sql: true
logging:
  level:
    org:
      hibernate: 
        type: trace
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8191/oauth/check_token
      
    client:
      client-id: web
      client-secret: web
      
server:
  port: 9090
  
  